import { Controller, Post, Get, Param, Body, HttpCode, HttpStatus } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiSecurity } from '@nestjs/swagger';
import { ComplianceService } from './compliance.service';
import { CurrentMerchant } from '../../common/decorators/current-merchant.decorator';

@ApiTags('Compliance')
@ApiSecurity('ApiKey')
@Controller({ path: 'compliance', version: '1' })
export class ComplianceController {
  constructor(private readonly complianceService: ComplianceService) {}

  @Post('screen')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Screen a merchant',
    description: 'Run a merchant through global sanctions lists (UN, OFAC, EU, UK), PEP databases, and local blacklists. Returns a risk score and any matches found.',
  })
  @ApiResponse({ status: 200, description: 'Screening completed' })
  async screenMerchant(@CurrentMerchant('id') merchantId: string) {
    const data = await this.complianceService.screenMerchant(merchantId);
    return { status: true, message: 'Screening completed', data };
  }

  @Get('screenings')
  @ApiOperation({ summary: 'List screenings', description: 'View all compliance screening records.' })
  async listScreenings(@CurrentMerchant('id') merchantId?: string) {
    const data = await this.complianceService.listScreenings(merchantId);
    return { status: true, message: 'Screenings retrieved', data };
  }

  @Get('alerts')
  @ApiOperation({
    summary: 'List AML alerts',
    description: 'View all suspicious transaction alerts generated by the AML monitoring engine.',
  })
  async listAlerts(@CurrentMerchant('id') merchantId?: string) {
    const data = await this.complianceService.listMonitoringAlerts(merchantId);
    return { status: true, message: 'Alerts retrieved', data };
  }

  @Post('screenings/:id/review')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Review screening',
    description: 'Manually review and clear/flag a compliance screening result.',
  })
  async reviewScreening(@Param('id') id: string, @Body() dto: any) {
    const data = await this.complianceService.reviewScreening(id, dto);
    return { status: true, message: 'Screening reviewed', data };
  }
}
